/* Generated By:JavaCC: Do not edit this line. WraptermsConstants.java */
package parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WraptermsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_testName = 4;
  /** RegularExpression Id. */
  int T_baseDirectory = 5;
  /** RegularExpression Id. */
  int T_dirGraph = 6;
  /** RegularExpression Id. */
  int T_dirLog = 7;
  /** RegularExpression Id. */
  int T_dirConceptMap = 8;
  /** RegularExpression Id. */
  int T_nameUserTermsFile = 9;
  /** RegularExpression Id. */
  int T_minIterationToVerifyUniqueConnectedComponent = 10;
  /** RegularExpression Id. */
  int T_minIterationToVerifyRelationshipBetweenOriginalConcepts = 11;
  /** RegularExpression Id. */
  int T_maxIteration = 12;
  /** RegularExpression Id. */
  int T_additionNewConceptWithoutCategory = 13;
  /** RegularExpression Id. */
  int T_kCoreFilter = 14;
  /** RegularExpression Id. */
  int T_quantityNodesToApplyKcoreFilter = 15;
  /** RegularExpression Id. */
  int T_nDegreeFilter = 16;
  /** RegularExpression Id. */
  int T_iterationTriggerApplyNDegreeFilterAlgorithm = 17;
  /** RegularExpression Id. */
  int T_quantityNodesToApplyNdegreeFilter = 18;
  /** RegularExpression Id. */
  int T_conceptsQuantityCalculationFactor = 19;
  /** RegularExpression Id. */
  int T_conceptsMinMaxRange = 20;
  /** RegularExpression Id. */
  int T_proporcionBetweenness = 21;
  /** RegularExpression Id. */
  int T_proporcionBetweennessCloseness = 22;
  /** RegularExpression Id. */
  int T_precisionBetweennessCloseness = 23;
  /** RegularExpression Id. */
  int T_maxBetweennessCloseness = 24;
  /** RegularExpression Id. */
  int T_proporcionEigenvector = 25;
  /** RegularExpression Id. */
  int T_precisionEigenvector = 26;
  /** RegularExpression Id. */
  int T_maxEigenvector = 27;
  /** RegularExpression Id. */
  int T_isBetweennessCloseness = 28;
  /** RegularExpression Id. */
  int T_isEigenvector = 29;
  /** RegularExpression Id. */
  int T_isSelected = 30;
  /** RegularExpression Id. */
  int T_isKeepNeighborsOfOriginalConcepts = 31;
  /** RegularExpression Id. */
  int T_quantityNodesShortReport = 32;
  /** RegularExpression Id. */
  int T_backGroundcolorOriginalConcept = 33;
  /** RegularExpression Id. */
  int T_borderThicknessConceptWithHint = 34;
  /** RegularExpression Id. */
  int T_nameGexfGraphFile = 35;
  /** RegularExpression Id. */
  int T_nameQueryDefaultFile = 36;
  /** RegularExpression Id. */
  int T_nameVocabularyFile = 37;
  /** RegularExpression Id. */
  int T_nameUselessConceptsFile = 38;
  /** RegularExpression Id. */
  int T_nameTxtConceptMapFile = 39;
  /** RegularExpression Id. */
  int T_nameCxlConceptMapFile = 40;
  /** RegularExpression Id. */
  int T_nameCompleteReportFile = 41;
  /** RegularExpression Id. */
  int T_nameShortReportFile = 42;
  /** RegularExpression Id. */
  int T_nameConsoleReportFile = 43;
  /** RegularExpression Id. */
  int T_nameConsoleErrorFile = 44;
  /** RegularExpression Id. */
  int T_dirRdfsPersistenceFiles = 45;
  /** RegularExpression Id. */
  int T_dbpediaServer = 46;
  /** RegularExpression Id. */
  int T_gephiVisualization = 47;
  /** RegularExpression Id. */
  int T_graphStreamVisualization = 48;
  /** RegularExpression Id. */
  int T_isFixBugInGephiToolKit = 49;
  /** RegularExpression Id. */
  int T_originalConceptWithGephiToolKitBug = 50;
  /** RegularExpression Id. */
  int T_isEnableUselessTable = 51;
  /** RegularExpression Id. */
  int EQUALS = 52;
  /** RegularExpression Id. */
  int NEW_LINE = 53;
  /** RegularExpression Id. */
  int TAB = 54;
  /** RegularExpression Id. */
  int BLANK = 55;
  /** RegularExpression Id. */
  int ARROW = 56;
  /** RegularExpression Id. */
  int COMMON_CHARACTER = 57;
  /** RegularExpression Id. */
  int SPECIAL_CHARACTER = 58;
  /** RegularExpression Id. */
  int TERM = 59;
  /** RegularExpression Id. */
  int SEPARATORS = 60;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int comentario_final = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "\"\\n\"",
    "<token of kind 3>",
    "\"testName\"",
    "\"baseDirectory\"",
    "\"dirGraph\"",
    "\"dirLog\"",
    "\"dirConceptMap\"",
    "\"nameUserTermsFile\"",
    "\"minIterationToVerifyUniqueConnectedComponent\"",
    "\"minIterationToVerifyRelationshipBetweenOriginalConcepts\"",
    "\"maxIteration\"",
    "\"additionNewConceptWithoutCategory\"",
    "\"kCoreFilter\"",
    "\"quantityNodesToApplyKcoreFilter\"",
    "\"nDegreeFilter\"",
    "\"iterationTriggerApplyNDegreeFilterAlgorithm\"",
    "\"quantityNodesToApplyNdegreeFilter\"",
    "\"conceptsQuantityCalculationFactor\"",
    "\"conceptsMinMaxRange\"",
    "\"proporcionBetweenness\"",
    "\"proporcionBetweennessCloseness\"",
    "\"precisionBetweennessCloseness\"",
    "\"maxBetweennessCloseness\"",
    "\"proporcionEigenvector\"",
    "\"precisionEigenvector\"",
    "\"maxEigenvector\"",
    "\"isBetweennessCloseness\"",
    "\"isEigenvector\"",
    "\"isSelected\"",
    "\"isKeepNeighborsOfOriginalConcepts\"",
    "\"quantityNodesShortReport\"",
    "\"backGroundcolorOriginalConcept\"",
    "\"borderThicknessConceptWithHint\"",
    "\"nameGexfGraphFile\"",
    "\"nameQueryDefaultFile\"",
    "\"nameVocabularyFile\"",
    "\"nameUselessConceptsFile\"",
    "\"nameTxtConceptMapFile\"",
    "\"nameCxlConceptMapFile\"",
    "\"nameCompleteReportFile\"",
    "\"nameShortReportFile\"",
    "\"nameConsoleReportFile\"",
    "\"nameConsoleErrorFile\"",
    "\"dirRdfsPersistenceFiles\"",
    "\"dbpediaServer\"",
    "\"gephiVisualization\"",
    "\"graphStreamVisualization\"",
    "\"isFixBugInGephiToolKit\"",
    "\"originalConceptWithGephiToolKitBug\"",
    "\"isEnableUselessTable\"",
    "<EQUALS>",
    "<NEW_LINE>",
    "<TAB>",
    "\" \"",
    "\"->\"",
    "<COMMON_CHARACTER>",
    "<SPECIAL_CHARACTER>",
    "<TERM>",
    "<SEPARATORS>",
  };

}
