/* Generated By:JavaCC: Do not edit this line. WraptermsConstants.java */
package basic;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WraptermsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHARACTER = 1;
  /** RegularExpression Id. */
  int TERM = 2;
  /** RegularExpression Id. */
  int SEPARATORS = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CHARACTER>",
    "<TERM>",
    "<SEPARATORS>",
  };

}
