/* Generated By:JavaCC: Do not edit this line. WraptermsConstants.java */
package basic;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WraptermsConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHARACTER_TERM = 1;
  /** RegularExpression Id. */
  int USER_TERM = 2;
  /** RegularExpression Id. */
  int SEPARATORS = 3;
  /** RegularExpression Id. */
  int CHARACTER_VOCABULARY = 4;
  /** RegularExpression Id. */
  int TERM_VOCABULARY = 5;
  /** RegularExpression Id. */
  int ARROW = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CHARACTER_TERM>",
    "<USER_TERM>",
    "<SEPARATORS>",
    "<CHARACTER_VOCABULARY>",
    "<TERM_VOCABULARY>",
    "\"->\"",
  };

}
